[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
solc = '0.7.6'
evm_version = 'istanbul'
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
